[package]
name = "ch02_tcp_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mylib = { path = "../mylib" }
clap = { version = "4", features = ["derive"] }
tracing = { version = "0.1" }
